### ISSUE TITLE
Running node server.js in the root-directory meanGetTogether throws an error in module.js when using AWS

### ISSUE THREAD

**Issue by Duc-Ngo-CSSE** [GetTogetherApp/meanGetTogether#2]
Here is the error log:

ec2-user@ip-172-31-36-56 meanGetTogether]$ node server.js

module.js:340
    throw err;
    ^
Error: Cannot find module './models/gps'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ec2-user/meanGetTogether/app/routes.js:1:78)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by Duc-Ngo-CSSE** [comment]
I tried Taran's suggestion. It doesn't look like an absolute path solves it:

[ec2-user@ip-172-31-36-56 meanGetTogether]$ node server.js

module.js:340
    throw err;
    ^
Error: Cannot find module '/home/ec2-user/meanGetTogether/app/models/gps'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ec2-user/meanGetTogether/app/routes.js:2:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by Duc-Ngo-CSSE** [comment]
After following Taran's suggestion to change the require file names (without extensions) in the 2nd line of routes.js to match their casing (upper case versus lower case), it solved the problem but gave a new error.

gps was changed to GPS to match the GPS.js file  in /app/models/ directory

[ec2-user@ip-172-31-36-56 meanGetTogether]$ node server.js

/home/ec2-user/meanGetTogether/app/models/GPS.js:1
(function (exports, require, module, __filename, __dirname) {  grab the mongoo
                                                                    ^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ec2-user/meanGetTogether/app/routes.js:2:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by Duc-Ngo-CSSE** [comment]
That solved the issue. Thanks, Taran.
